# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vic-Dev
email: vmichellej@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog details my trials and tribulations in this continuous journey to learn to code.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://vic-dev.github.io/" # the base hostname & protocol for your site
twitter_username: _VicDev
github_username:  Vic-Dev

# Build settings
markdown: kramdown
